<a href="https://colab.research.google.com/github/Inafamoo/Studi-Independem/blob/main/Inafamo_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

# Creating Arrays

In [1]:
# Import Library NumPy
import numpy as np

# Contoh Membuat Array
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [2]:
a

array([1, 2, 3])

In [3]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [8]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [10]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [11]:
np.random.random((2,2))

array([[0.76645243, 0.66292952],
       [0.71263999, 0.8415732 ]])

In [12]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

# Input Output

### Saving & Loading On Disk

In [13]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [14]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

# Data Types

In [15]:
np.int64

numpy.int64

In [16]:
np.float32

numpy.float32

In [17]:
np.complex

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


complex

In [18]:
np.bool

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


bool

In [19]:
np.object

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


object

In [20]:
np.string_

numpy.bytes_

In [21]:
np.unicode_

numpy.str_

# Inspecting Your Array 

In [22]:
a.shape

(3,)

In [23]:
len(a)

3

In [24]:
b.ndim

2

In [25]:
e.size

4

In [26]:
b.dtype

dtype('float64')

In [27]:
b.dtype.name

'float64'

In [28]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics
## Arithmetic Operations

### Subtraction

In [29]:
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [30]:
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

### Addition

In [31]:
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [32]:
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

### Division

In [33]:
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [34]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

### Multiplication

In [35]:
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [36]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

### Exponentiation

In [37]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

### Square root

In [38]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Print sines of an array

In [39]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Element-wise cosine 

In [40]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

### Element-wise natural logarithm

In [41]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

### Dot product

In [42]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## Comparison

### Element-wise comparison

In [43]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [44]:
a < 2

array([ True, False, False])

### Array-wise comparison

In [45]:
np.array_equal(a, b)

False

## Aggregate Functions

### Array-wise sum

In [46]:
a.sum()

6

### Array-wise minimum value

In [47]:
a.min()

1

### Maximum value of an array row

In [48]:
b.max(axis=0)

array([4., 5., 6.])

### Cumulative sum of the elements

In [49]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

### Mean

In [50]:
a.mean()

2.0

### Median 

In [51]:
np.median(b)

3.5

### Correlation coefficient

In [52]:
np.corrcoef(a)

1.0

### Standard deviation

In [53]:
np.std(b)

1.5920810978785667

# Copying Arrays

### Create a view of the array with the same data

In [54]:
h = a.view()
h

array([1, 2, 3])

### Create a copy of the array

In [55]:
np.copy(a)

array([1, 2, 3])

### Create a deep copy of the array

In [56]:
h = a.copy()
h

array([1, 2, 3])

# Sorting Arrays

### Sort an array

In [57]:
a.sort()
a

array([1, 2, 3])

### Sort the elements of an array's axis

In [58]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [59]:
a[2]

3

### Select the element at row 1 column 2 (equivalent to b[1][2])


In [60]:
b[1,2]

6.0

## Slicing

### Select items at index 0 and 1

In [61]:
a[0:2]

array([1, 2])

### Select items at rows 0 and 1 in column 1

In [62]:
b[0:2,1]

array([2., 5.])

### Select all items at row 0 (equivalent to b[0:1, :])

In [63]:
b[:1]

array([[1.5, 2. , 3. ]])

### Same as [1,:,:]

In [64]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

### Reversed array a 

In [65]:
a[ : :-1]

array([3, 2, 1])

# Array Manipulation

## Transposing Array

### Permute array dimensions

In [66]:
i = np.transpose(b)

In [67]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##  Changing Array Shape

### Flatten the array

In [68]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [69]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

### Reshape, but don’t change data

In [70]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [71]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

### Return a new array with shape (2,6) 

In [72]:
h

array([1, 2, 3])

In [73]:
np.resize(h, (2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Append items to an array

In [74]:
h

array([1, 2, 3])

In [75]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [76]:
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

### Insert items in an array

In [77]:
a

array([1, 2, 3])

In [78]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

### Delete items from an array

In [79]:
a

array([1, 2, 3])

In [80]:
np.delete(a,[1])

array([1, 3])

## Combining Arrays

###  Concatenate arrays

In [81]:
a

array([1, 2, 3])

In [82]:
d

array([10, 15, 20])

In [83]:
np.concatenate((a,d),axis=0) 

array([ 1,  2,  3, 10, 15, 20])

### Stack arrays vertically (row-wise)

In [84]:
a

array([1, 2, 3])

In [85]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [86]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Stack arrays vertically (row-wise)

In [87]:
e

array([[7, 7],
       [7, 7]])

In [88]:
f

array([[1., 0.],
       [0., 1.]])

In [89]:
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

### Stack arrays horizontally (column-wise)

In [90]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

### Create stacked column-wise arrays 

In [91]:
a

array([1, 2, 3])

In [92]:
d

array([10, 15, 20])

In [93]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Create stacked column-wise arrays

In [94]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

### Split the array horizontally at the 3rd index

In [95]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

### Split the array vertically at the 2nd index

In [96]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]

# Thank You