<a href="https://colab.research.google.com/github/Inafamoo/Studi-Independem/blob/main/Latihan_2_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1. Simpan data pada tabel di atas dalam sebuah dictionary! Lalu cetak dictionary yang sudah kamu buat!

In [ ]:
herman = {"NIK": 1990022, "Nama":"Herman", "jk":"L", "Alamat":"Tangerang", "Divisi":"Machinery","Jabatan":"Manager","GP":10000000} 
print(herman)
badar = {"NIK": 2001077, "Nama":"Badar", "jk":"L", "Alamat":"Bekasi", "Divisi":"Machinery","Jabatan":"Staff","GP":7500000} 
print(badar)
clara = {"NIK": 2002019, "Nama":"Clara", "jk":"P", "Alamat":"Depok", "Divisi":"Compressor","Jabatan":"Staff","GP":7000000} 
print(clara)
rista = {"NIK": 2002081, "Nama":"Rista", "jk":"P", "Alamat":"Bogor", "Divisi":"QC","Jabatan":"Staff","GP":6500000} 
print(rista)
riani = {"NIK": 2005099, "Nama":"Riani", "jk":"P", "Alamat":"Bekasi", "Divisi":"QC","Jabatan":"Operator","GP":6000000} 
print(riani)
afif = {"NIK": 2006003, "Nama":"Afif", "jk":"L", "Alamat":"Karawang", "Divisi":"Compressor","Jabatan":"Operator","GP":5500000} 
print(afif)
riven = {"NIK": 2006104, "Nama":"Riven", "jk":"L", "Alamat":"Tangerang", "Divisi":"Compressor","Jabatan":"Operator","GP":5500000} 
print(riven)
endah = {"NIK": 2001077, "Nama":"Endah", "jk":"P", "Alamat":"Jakarta", "Divisi":"Machinery","Jabatan":"Operator","GP":5000000} 
print(endah)

{'NIK': 1990022, 'Nama': 'Herman', 'jk': 'L', 'Alamat': 'Tangerang', 'Divisi': 'Machinery', 'Jabatan': 'Manager', 'GP': 10000000}
{'NIK': 2001077, 'Nama': 'Badar', 'jk': 'L', 'Alamat': 'Bekasi', 'Divisi': 'Machinery', 'Jabatan': 'Staff', 'GP': 7500000}
{'NIK': 2002019, 'Nama': 'Clara', 'jk': 'P', 'Alamat': 'Depok', 'Divisi': 'Compressor', 'Jabatan': 'Staff', 'GP': 7000000}
{'NIK': 2002081, 'Nama': 'Rista', 'jk': 'P', 'Alamat': 'Bogor', 'Divisi': 'QC', 'Jabatan': 'Staff', 'GP': 6500000}
{'NIK': 2005099, 'Nama': 'Riani', 'jk': 'P', 'Alamat': 'Bekasi', 'Divisi': 'QC', 'Jabatan': 'Operator', 'GP': 6000000}
{'NIK': 2006003, 'Nama': 'Afif', 'jk': 'L', 'Alamat': 'Karawang', 'Divisi': 'Compressor', 'Jabatan': 'Operator', 'GP': 5500000}
{'NIK': 2006104, 'Nama': 'Riven', 'jk': 'L', 'Alamat': 'Tangerang', 'Divisi': 'Compressor', 'Jabatan': 'Operator', 'GP': 5500000}
{'NIK': 2001077, 'Nama': 'Endah', 'jk': 'P', 'Alamat': 'Jakarta', 'Divisi': 'Machinery', 'Jabatan': 'Operator', 'GP': 5000000}


In [ ]:
2. Buat sebuah array dengan elemen seperti gambar di bawah! Kemudian lakukan slicing pada array tersebut sesuai dengan arahan kotak merah!

In [ ]:
import numpy as np
no_2 = np.array ([[1,2],
                  [4,5],
                  [7,8]])
print (no_2[2,:])

[7 8]


In [ ]:
3. Buat sebuah array dengan elemen seperti gambar di bawah! Kemudian lakukan slicing pada array tersebut sesuai dengan arahan kotak merah!

In [ ]:
import numpy as np
no_3 = np.array ([[1,2],
                  [6,5],
                  [9,8]])
print (no_3[1,:])

[6 5]


In [ ]:
4. Buat sebuah array dengan elemen seperti gambar di bawah! Kemudian lakukan slicing pada array tersebut sesuai dengan arahan kotak merah!

In [ ]:
import numpy as np
A = np.array ([[4,7,6],
              [3,2,1],
              [8,5,9]])
print (A[1,1:3 ])

[2 1]


In [ ]:
import numpy as np
B = np.array ([[4,3,8],
              [7,2,5],
              [6,1,9]])
print (B[0,1:3 ])

[3 8]


In [ ]:
5. Buat sebuah array dengan elemen seperti gambar di bawah! Kemudian lakukan slicing pada array tersebut sesuai dengan arahan kotak merah!

In [ ]:
import numpy as np
A= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (A[1, 1:4])

[44 11 83]


In [ ]:
import numpy as np
B= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (B[2:4, 1:3])

[[12 46]
 [67 65]]


In [ ]:
import numpy as np
C= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (C[1:4 , 1:4])

[[44 11 83]
 [12 46 28]
 [67 65 32]]


In [ ]:
import numpy as np
D= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (D[1:3, 0:2])

[[92 44]
 [40 12]]


In [ ]:
import numpy as np
E= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (E[0:2, 0:3])

[[23 35 93]
 [92 44 11]]


In [ ]:
import numpy as np
F= np.array ([[23,35,93,87],
              [92,44,11,83],
              [40,12,46,28],
              [73,67,65,32]])
print (F[1:4, 1:2])

[[44]
 [12]
 [67]]
